### ISSUE TITLE
Sorry for posting this here, but ...

### ISSUE THREAD

**Issue by Noemata** [ahmed605/Sensei.NET#1]
I didn't see any other way to reach you about this.  Will you be publishing the source to your ScreenSenderComponent lib?

**Comment by ahmed605** [comment]
@Noemata 
Hi,
Unfortunately I can't release the source of ScreenSenderComponent lib because it's not mine
This library is written by Ryken (Christopher Blackman, the creator of myTube) so you can contact him to ask him about the lib (he's on Discord)

Just curious, from where did you hear about that lib?

**Comment by Noemata** [comment]
Thanks for the ref and info.  No worries on the "late reply", it's way faster than some.  Sorry for intruding into this repo this way.  I am open to exchanging emails, since it seems there may be other relevant conversations in the future.

**Comment by ahmed605** [comment]
@Noemata if you mean exchanging emails with me by "exchanging emails" sure my email is ahmed.walid605@yahoo.com
But I will 90% not see your message as I don't check my email regularly so I don't recommend communicating using it
If you have Twitter or Discord (or even continuing the conversation here) it would be much better

**Comment by Noemata** [comment]
Fair enough.  I was hoping to have a slightly more private channel to start.  I'm open to suggestions.  One of the things I wanted to run by you is the prospect of starting a WinUI streering group that sits outside of Microsoft.  XAML fragmentation has been a problem for quite some time now.  Since Microsoft has been the principle contributor to this fragmentation, I think it's time XAML devs start speaking with one voice.

**Comment by Noemata** [comment]
(these posts have visibility to anyone that is a follower)

**Comment by Noemata** [comment]
On Discord as: Noemata#7618

**Comment by ahmed605** [comment]
> On Discord as: Noemata#7618
> 
> 
@Noemata sent you a friend request (from: Ahmed 605#2490)

**Comment by Noemata** [comment]
Added, you can delete this thread.
